# install and configure ufw, nginx, /var/www
- name: setup ufw, nginx
  hosts: all
  become: true

  tasks:

    - name: install and configure ufw
      ansible.builtin.import_tasks:
        file: ./tasks/ufw.yaml

    - name: install and configure nginx
      ansible.builtin.include_role:
        name: nginxinc.nginx_core.nginx

    - name: copy replacement nginx default config
      ansible.builtin.copy:
        src: ./files/default.conf
        dest: /etc/nginx/conf.d/default.conf
        force: true
        mode: preserve

    - name: remove /var/www
      ansible.builtin.file:
        path: /var/www
        state: absent

    - name: create /vagrant symbolic link over /var/www
      ansible.builtin.file:
        src: /vagrant
        dest: /var/www
        state: link

    - name: ufw - allow ssh connections
      community.general.ufw:
        rule: allow
        name: "WWW Full"
